package com.taskninjapro.android.task;

public enum TaskLong {
	KEY_SINGLE_QUEUING, KEY_RECURRING_QUEUING, KEY_COMPLETED, KEY_DUE_DATE, KEY_SINGLE_ALERT, KEY_SINGLE_ALERT_TIME, KEY_RECURRING_ALERT_TIME, KEY_SINGLE_QUEUING_TIME, KEY_RECURRING_QUEUING_TIME

}
