package com.taskninjapro.android.task;

public enum TaskBool {
	// Google Tasks
	hidden,
	
	// Task Ninja Tasks
	KEY_SINGLE_QUEUING, 
	KEY_RECURRING_QUEUING, 
	KEY_SINGLE_QUEUEING_FRONT, 
	KEY_RECURRING_QUEUING_FRONT, 
	KEY_COMPLETED, 
	KEY_SINGLE_ALERT, 
	KEY_RECURRING_ALERT, 
	KEY_RECURRING_ALERT_MONDAY, 
	KEY_RECURRING_ALERT_TUESDAY, 
	KEY_RECURRING_ALERT_WEDNESDAY, 
	KEY_RECURRING_ALERT_THURSDAY, 
	KEY_RECURRING_ALERT_FRIDAY, 
	KEY_RECURRING_ALERT_SATURDAY, 
	KEY_RECURRING_ALERT_SUNDAY, 
	KEY_RECURRING_QUEUING_MONDAY, 
	KEY_RECURRING_QUEUING_TUESDAY, 
	KEY_RECURRING_QUEUING_WEDNESDAY, 
	KEY_RECURRING_QUEUING_THURSDAY, 
	KEY_RECURRING_QUEUING_FRIDAY, 
	KEY_RECURRING_QUEUING_SATURDAY, 
	KEY_RECURRING_QUEUING_SUNDAY, 
	KEY_QUEUING

}
